### ISSUE TITLE
Consider adding twostage.admissible() results directly in ph2simon() function return

### ISSUE THREAD

**Issue by karissawhiting** [veseshan/clinfun#20]
Currently it's just in the print statement and you can't access things like `qlo` and `qhigh` otherwise. We could instead run this internal function in ph2simon() and return as an additional matrix (like `out`).

**Comment by veseshan** [comment]
Agreed. Call can be moved from print method to the function itself.

**Comment by veseshan** [comment]
Changes made and committed to cran branch.
